services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    runtime: nvidia
    ports:
      - "8200:8000"
    environment:
      - NCCL_P2P_DISABLE=1
      - NCCL_IB_DISABLE=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model cyankiwi/AWQ-4BIT
      --max-model-len 81920
      --max-num-seqs 4
      --async-scheduling
      --dtype auto
      --kv-cache-dtype fp8
      --enable-expert-parallel
      --trust-remote-code
      --tensor-parallel-size 4
      --enable-chunked-prefill
      --enable-prefix-caching
      --trust-remote-code
      --reasoning-parser nemotron_v3
      --enable-auto-tool-choice
      --tool-call-parser qwen3_xml
    restart: unless-stopped
    ipc: host